language: haskell
ghc: 7.8


# Install GHC 7.8.2 on Travis using hvr's repo, see
# https://github.com/hvr/multi-ghc-travis
before_install:
      - ghc --version
      - cabal --version
      - sudo add-apt-repository -y ppa:hvr/ghc
      - sudo apt-get update
      - sudo apt-get install cabal-install-1.20
      - export PATH=/opt/cabal/1.20/bin:$PATH
      - ghc --version
      - cabal --version

install:
      - cabal sandbox init
      - cabal install -j --only-dependencies --ghc-options=-w
      - cabal configure

script:
      - make all

after_success:
      - make haddock
      # run tests



notifications:
      email: false